name: Build and Push to AWS ECR

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Update if your region is different

      - name: Login to AWS Public ECR
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws

      - name: Build Docker Image with Arguments
        run: |
          docker build --build-arg DB_URL=${{ secrets.DB_URL }} \
                       --build-arg DB_USERNAME=${{ secrets.DB_USERNAME }} \
                       --build-arg DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
                       -t ${{ secrets.ECR_REPOSITORY }}:latest .

      - name: Tag Docker Image
        run: |
          docker tag ${{ secrets.ECR_REPOSITORY }}:latest public.ecr.aws/${{ secrets.ECR_REPOSITORY }}:latest

      - name: Push Docker Image to AWS ECR
        run: |
          docker push public.ecr.aws/${{ secrets.ECR_REPOSITORY }}:latest
